### ISSUE TITLE
Moving from User:Password to IAM Apikey

### ISSUE THREAD

**Issue by vperrinfr** [solinftec/watson-instance-pusher#2]
Watson Services have migrated to IAM apikey instead of user:password.
It would be good to leverage it for new WA service.

In **watson-assistant-service.js**

Replace

```
export class WatsonAssistantService { 
  constructor(credentials) {
  this._assistant = new AssistantV1({
  username: credentials.username,
  password: credentials.password,
  version: credentials.version
  });
}
```

by

```
this._assistant = new AssistantV1({
  version: '2018-09-20',
  iam_apikey: '{apikey}',
  url: '{url}'
});
```

**Comment by GledsonAfonso** [comment]
Thanks for the heads up @vperrinfr and sorry for the late response! I will see into it and make the necessary changes.

**Comment by GledsonAfonso** [comment]
The `backup-job.js` needs some testing, but the endpoints are working with the new IAM now.

**Comment by GledsonAfonso** [comment]
Done! The endpoints and service jobs are working with the new IAM now.
